const USER_FETCH_REQUEST = "USER_FETCH_REQUEST"
const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS"
const USER_FETCH_ERROR = "USER_FETCH_ERROR"
const DELETE_USER = "DELETE_USER"
const ADD_USER = "ADD_USER"
const GET_USER = "GET_USER"
const UPDATE_USER = "UPDATE_USER"
export {
    USER_FETCH_REQUEST,
    USER_FETCH_SUCCESS,
    USER_FETCH_ERROR,
    DELETE_USER,
    ADD_USER,
    GET_USER,
    UPDATE_USER
}